version: '3.8'

services:
  app:
    container_name: flipse-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_POSTHOG_KEY=${VITE_POSTHOG_KEY}
        - VITE_POSTHOG_HOST=${VITE_POSTHOG_HOST}
    ports:
      - "5173:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_POSTHOG_KEY=${VITE_POSTHOG_KEY}
      - VITE_POSTHOG_HOST=${VITE_POSTHOG_HOST}
    networks:
      - flipse-network

networks:
  flipse-network:
    driver: bridge
